# Site settings
title: Hector ’s Blog
SEOTitle: Hector.Z的博客 | Hector.Z Blog
header-img: img/home-bg.jpg
email: 418918345@qq.com
description: "May Your Heart Be The Map"
keyword: ""
url: "https://hectoor.github.io/"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
# weibo_username:   
github_username:    Hectoor  
#zhihu_username:     
#twitter_username:  
#facebook_username:  



# Build settings
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
gems: [jekyll-paginate]


# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
duoshuo_username: Bebop.C
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: false                     # set to false if you want to use Comment without Sharing







# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "一定会更疯狂。"
sidebar-avatar: /img/hector.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "Bebop.C Blog",
        href: "#"
    },{
        title: "Spike Spiegel",
        href: "#"
    },{
        title: "Jet Black",
        href: "#"
    },{
        title: "Faye Valentine",
        href: "#"
    },{
        title: "Ein",
        href: "#"
    }
]
